### PR TITLE
Wrapped php_uname call in function_exists as per @moorscode's suggestion

### LINKED ISSUE #8: PHP segfault in class-helpscout-beacon-identifier
In the `class-helpscout-beacon-identifier` there are parameters added to the `php_uname( )` function.

This causes a PHP segfault error in PHP 7.2.7. Removing the parameters solves the issue.

### PR DESCRIPTION
**Pull request by jcomack**
## Summary

This PR can be summarized in the following changelog entry:

* Wraps `php_uname` call in a `function_exists` to prevent errors on certain server configurations.

Fixes #8 
Fixes https://github.com/Yoast/wordpress-seo/issues/11474

### CODE REVIEW

File: src/class-helpscout-beacon-identifier.php [hunk 1]
```diff
@@ -58,7 +58,11 @@ private function get_server_info() {
 			$out .= '<tr><td>IP</td><td>' . $ipaddress . '</td></tr>';
 			$out .= '<tr><td>Hostname</td><td>' . gethostbyaddr( $ipaddress ) . '</td></tr>';
 		}
-		$out .= '<tr><td>OS</td><td>' . php_uname( 's r' ) . '</td></tr>';
+
+		if ( function_exists( 'php_uname' ) {
+			$out .= '<tr><td>OS</td><td>' . php_uname( 's r' ) . '</td></tr>';
```
Comment (dutchmartin) [inline src/class-helpscout-beacon-identifier.php]: If i am correct, this fix prevents errors on servers where the function `php_uname` is disabled for security reasons.
Maybe displaying a unable to fetch os messsage is wanted behavior, but this seems fine for now.

**Comment by moorscode** [comment]
Creating a zip for Premium, which includes this fix. After confirmation that it solves the problem, we can merge and bump the versions in the plugins that use this tool.
